### ISSUE TITLE
Silent Notification

### ISSUE THREAD

**Issue by eduardobonfa** [googlesamples/android-NotificationChannels#14]
I tried to set sound of one of the channels to null, but it is still notification with sound. Is there a way to silent one of the channel programmatically?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
