### ISSUE TITLE
Language switching support + Channels

### ISSUE THREAD

**Issue by PaulRashidi** [googlesamples/android-NotificationChannels#15]
Please update the sample to show the optimal way to deal with multiple languages. 

Seems like you have three choices:
1.) Track which language you created it with and call create again with an updated channel when it changes.
2.) Retrieve the channel before posting and comparing the same way as #1 but you don't have to store anything.
3.) Simply always call create to maintain simpler code (if the underlying implementation is fast enough).

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
