### ISSUE TITLE
setSmallIcon设置自定义的图片后通知栏展示纯灰色

### ISSUE THREAD

**Issue by lzyang187** [googlesamples/android-NotificationChannels#16]
我的代码如下：
NotificationChannel channel = new NotificationChannel(PRIMARY_CHANNEL_ID, "消息通知", NotificationManager.IMPORTANCE_DEFAULT);
            mgr.createNotificationChannel(channel);
            notification = new Notification.Builder(context, PRIMARY_CHANNEL_ID)
                    .setSmallIcon(R.mipmap.icon_notify)
                    .setTicker(ticker)
                    .setWhen(System.currentTimeMillis())
                    .build();
然而通知栏的效果不符合预期：
![image](https://user-images.githubusercontent.com/15063869/34402222-42b5a890-ebdb-11e7-8a54-a27156d7389a.png)

**Comment by aniaForever** [comment]
我也遇到这个问题了

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
