### ISSUE TITLE
How to turn off vibrations on Android O

### ISSUE THREAD

**Issue by azhon** [googlesamples/android-NotificationChannels#18]
How to turn off vibrations on Android O

**Comment by dave2dee** [comment]
if you are talking about the main notifications go into settings, apps and notifications, app info, messages, app notifications and then you have to go into each and every category and UN check vibration.
                but if you talk about specific app so there is a global Vibrate option for the SMS app, just go to Messages > Settings > Notifications (it would open the Default Notification Channel) > Turn off Vibrate
even for each single app so its a little noisy but it works

**Comment by azhon** [comment]
on Oreo, When I create one progress-notification by following code
`
NotificationChannel channel = new NotificationChannel("appupdate", "版本更新",
                    NotificationManager.IMPORTANCE_DEFAULT);
channel.enableVibration(false);
manager.createNotificationChannel(channel);

`
build Notification
`
NotificationCompat.Builder builder = builderNotification(context, icon, title, content)
                .setProgress(max, progress, false);
        manager.notify(DownloadManager.getInstance().getConfiguration().getNotifyId(), builder.build());

private static NotificationCompat.Builder builderNotification(Context context, int icon, String title, String content) {
        return new NotificationCompat.Builder(context, "appupdate")
                .setSmallIcon(icon)
                .setContentTitle(title)
                .setWhen(System.currentTimeMillis())
                .setContentText(content)
                .setAutoCancel(false)
                .setOngoing(true);
    }
`
result：
the phone always vibrates while updating, so how can I turn off vibrations and sounds?

**Comment by Wang-Jong** [comment]
Solved?
I face the same problem. Help!

**Comment by azhon** [comment]
Set the importance params of NotificationChannel to NotificationManager.IMPORTANCE_LOW

**Comment by Wang-Jong** [comment]
Thanks. It works for me.

**Comment by FaakhirIqbal** [comment]
https://stackoverflow.com/a/52207215/1352919
