### ISSUE TITLE
Add pre 26 support

### ISSUE THREAD

**Issue by behelit** [googlesamples/android-NotificationChannels#19]
Since this is the goto for Oreo/Channel support code, I think it would be highly recommended to show how to correctly support SDK's lower than 26 in the sample code rather than forcing everyone to use 26+

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
