### ISSUE TITLE
@mipmap/ic_launcher Missing

### ISSUE THREAD

**Issue by commonsguy** [googlesamples/android-NotificationChannels#2]
The manifest has `android:icon="@mipmap/ic_launcher"` in the `<application>` element. There are no `mipmap` resources in the project. As a result, the project raises errors immediately upon import.

**Comment by tjohns** [comment]
Acknowledged. Will be fixed in next release.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
