### ISSUE TITLE
customer notification sound does`t work in Android O

### ISSUE THREAD

**Issue by gaoneng102** [googlesamples/android-NotificationChannels#22]
it dose`t work following:
```java
AudioAttributes attributes = new AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_NOTIFICATION)
                .build();
Uri sound = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://" + getPackageName() + "/" + R.raw.vehicle_alarm);
chan1.setSound(sound, attributes);
```
somthing else i can chang the sound i want!!

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
