### ISSUE TITLE
NotificationManagerCompat group/channel method missing

### ISSUE THREAD

**Issue by desugar-64** [googlesamples/android-NotificationChannels#6]
Why `NotificationCompat.Builder` has method to set channel id but `NotificationManagerCompat` can't create a channel?

`https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#NotificationCompat.Builder(android.content.Context, java.lang.String)`
`https://developer.android.com/reference/android/support/v4/app/NotificationManagerCompat.html`

**Comment by zunpiau** [comment]
It seem that the mothod `setChannel` in `NotificationCompat.Builder` don't work. Use `Notification.Builder` instead.

**Comment by mahendramahi** [comment]
@zunpiau Thanks bro ... save my day

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
