### ISSUE TITLE
missing .gitignore

### ISSUE THREAD

**Issue by bramley-turner-stride** [googlesamples/android-NotificationChannels#8]
Repo doesn't have a .gitignore file, which means the first time you run it Android Studio prompts to add hundreds of build / .idea files to git.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
