### ISSUE TITLE
getTitleSecondaryText() is wrong

### ISSUE THREAD

**Issue by nguyenhoainam91** [googlesamples/android-NotificationChannels#9]
In _android-NotificationChannels/Application/src/main/java/com/example/android/notificationchannels/**MainActivity.java**_

```
private String getTitleSecondaryText() {
            if (titlePrimary != null) {
                return titleSecondary.getText().toString();
            }
            return "";
}
```

proposed change:

```
private String getTitleSecondaryText() {
            if (titleSecondary!= null) {
                return titleSecondary.getText().toString();
            }
            return "";
}

```

**Comment by MarcinMoskala** [comment]
I also noticed it in Kotlin clean-up.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
